apiVersion: skaffold/v4beta13
kind: Config

manifests:
  rawYaml:
    - infra/k8s/*
    - infra/k8s-dev/*
    - infra/k8s-argo-apps/*
    - infra/k8s-databases/*
    - infra/k8s-volumes/*
#    - infra/k8s-monitor/dashboard-admin.yml
#    - infra/k8s-monitor/dashboard.yml
#    - infra/k8s-monitor/ingress-dashboard.yml
deploy:
  kubectl: {}

build:
  local:
    push: true
    useBuildkit: true
  platforms: ["linux/amd64"]

  tagPolicy:
    customTemplate:
      template: latest

  artifacts:
    - image: willnguyen/glassdoor-server
      context: server
      platforms: ["linux/amd64"]
      docker:
        dockerfile: Dockerfile

      sync:
        manual:
          - src: "app/**/*.erb"
            dest: "app"
          - src: "lib/**/*.erb"
            dest: "lib"
          - src: "config/**/*.rb"
            dest: "config"
          - src: "Gemfile"
            dest: "."
          - src: "Gemfile.lock"
            dest: "."
    - image: willnguyen/glassdoor-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: # listen for files changes and deploy to dest which is in container
        manual:
          - src: '**/*.js'
            dest: .
#  hooks:
#    after:
#      - command:
#        - kubectl
#        - exec
#        - deployment/server
#        - --
#        - bundle
#        - exec
#        - rails
#        - db:create
#      - command:
#        - kubectl
#        - exec
#        - deployment/server
#        - --
#        - bundle
#        - exec
#        - rails
#        - db:migrate

portForward:
  - resourceType: service
    resourceName: argocd-server
    port: 443
    localPort: 8080
#  - resourceType: service
#    resourceName: postgres
#    port: 5432
#    localPort: 5432
#  - resourceType: service
#    resourceName: elasticsearch
#    port: 9200
#    localPort: 9200
