default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "glassdoor") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "glassdoor") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "postgres") %>


development:
  <<: *default
  host: 127.0.0.1
  database: glassdoor_development
  username: glassdoor
  password: glassdoor

test:
  <<: *default
  host: 127.0.0.1
  database: glassdoor_test
  username: glassdoor
  password: glassdoor

production:
  primary: &primary_production
    <<: *default
    host: postgres
    database: glassdoor_development
    username: glassdoor
    password: glassdoor
  cache:
    <<: *primary_production
    database: server_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: server_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: server_production_cable
    migrations_paths: db/cable_migrate
