# argocd-controller-cluster-access.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-access
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - serviceaccounts
      - pods
      - persistentvolumeclaims
      - persistentvolumes
      - limitranges
      - resourcequotas
      - namespaces
      - volumeattachments
      - storageclasses
      - daemonsets
      - kongvaults
      - kongcustomentities
      - replicationcontrollers
      - csinodes
      - konglicenses
      - kongcustomentities
      - podtemplates
      - csidrivers
      - statefulsets
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - workflowtasksets
      - workfloweventbindings
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-access
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
