apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: willnguyen/glassdoor-server:1.2.14
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-key-base
                  key: SECRET_KEY_BASE
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_USER
              value: glassdoor
            - name: POSTGRES_PASSWORD
              value: glassdoor
            - name: POSTGRES_DB
              value: glassdoor_development
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
