apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
spec:
  project: default
  source:
    repoURL: https://github.com/nctruong/glassdoor.git
    targetRevision: HEAD
    path: infra/k8s-databases
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
