name: server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=1.2.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          cd server
#          docker build -t willnguyen/glassdoor-server:$IMAGE_TAG .
#          docker push willnguyen/glassdoor-server:$IMAGE_TAG

      - name: Update manifest and push to Git
        run: |
          sed -i "s|image: willnguyen/glassdoor-server:.*|image: willnguyen/glassdoor-server:${IMAGE_TAG}|" infra/k8s/server/server-depl.yml
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git commit -am "chore: update image to $IMAGE_TAG"
          echo "${{ secrets.TOKEN }}"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/nctruong/glassdoor.git
