name: tests

on:
  pull_request

env:
  RAILS_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server && bundle install && rails db:create && rails db:migrate && rspec
